"""Update UserPermission model to support both users and customers

Revision ID: 0cb1e75b354d
Revises: 39f7c3d3e995
Create Date: 2025-10-27 19:22:03.022965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cb1e75b354d'
down_revision = '39f7c3d3e995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(length=20), nullable=False))
        batch_op.drop_constraint(batch_op.f('user_permissions_user_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('user_permissions_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###
