"""Add last_update_by_manager_id to track manager updates

Revision ID: 30067a29eaa3
Revises: add_last_update_by
Create Date: 2025-12-04 11:49:51.721678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30067a29eaa3'
down_revision = 'add_last_update_by'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_update_by_manager_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'customers', ['last_update_by_manager_id'], ['id'])

    with op.batch_alter_table('emi_installments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_emi_account_due_date'))
        batch_op.drop_index(batch_op.f('idx_emi_account_paid'))
        batch_op.drop_constraint(batch_op.f('emi_installments_transaction_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'transactions', ['transaction_id'], ['id'])

    with op.batch_alter_table('transaction_edit_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.drop_index(batch_op.f('idx_edit_request_status'))
        batch_op.drop_index(batch_op.f('idx_edit_request_transaction_status'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_edit_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_edit_request_transaction_status'), ['transaction_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_edit_request_status'), ['status'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))

    with op.batch_alter_table('emi_installments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('emi_installments_transaction_id_fkey'), 'transactions', ['transaction_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_emi_account_paid'), ['account_id', 'is_paid'], unique=False)
        batch_op.create_index(batch_op.f('idx_emi_account_due_date'), ['account_id', 'due_date'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_update_by_manager_id')

    # ### end Alembic commands ###
