"""Add cascade delete to accounts foreign key

Revision ID: 38a7b3618525
Revises: 9763a74242ef
Create Date: 2025-10-24 19:12:32.967480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a7b3618525'
down_revision = '9763a74242ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('accounts_customer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('accounts_customer_id_fkey'), 'customers', ['customer_id'], ['id'])

    # ### end Alembic commands ###
