"""Add daily_contribution to accounts

Revision ID: 42b2c45c97ee
Revises: a4aa2493d72b
Create Date: 2025-12-24 16:12:11.094200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b2c45c97ee'
down_revision = 'a4aa2493d72b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_contribution', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('daily_contribution')

    # ### end Alembic commands ###
