"""Remove is_template column from account_types table

Revision ID: 590f2a661c94
Revises: fb4b538d3a81
Create Date: 2025-10-27 13:36:10.747298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590f2a661c94'
down_revision = 'fb4b538d3a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_types', schema=None) as batch_op:
        batch_op.drop_column('is_template')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_template', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
