"""Change document_path to Text for JSON storage

Revision ID: 5e1a1f9011bb
Revises: 88dcb75fa8b6
Create Date: 2025-12-31 12:42:11.016031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1a1f9011bb'
down_revision = '88dcb75fa8b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_types', schema=None) as batch_op:
        batch_op.alter_column('document_path',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_types', schema=None) as batch_op:
        batch_op.alter_column('document_path',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
