"""Update transactions table to support both users and customers as creators

Revision ID: 8459c1d41762
Revises: 50bde956187a
Create Date: 2025-10-28 16:34:48.381897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8459c1d41762'
down_revision = '50bde956187a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_type', sa.String(length=20), nullable=False))
        batch_op.drop_constraint(batch_op.f('transactions_created_by_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('transactions_created_by_fkey'), 'users', ['created_by'], ['id'])
        batch_op.drop_column('creator_type')

    # ### end Alembic commands ###
