"""Add role field to customers table

Revision ID: d06e3f1df9ab
Revises: ab5d26bcac39
Create Date: 2025-10-24 12:59:39.516322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06e3f1df9ab'
down_revision = 'ab5d26bcac39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
    
    # Update existing records to have 'staff' as default role
    op.execute("UPDATE customers SET role = 'staff' WHERE role IS NULL")
    
    # Now make the column NOT NULL
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('role', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
