"""Add structured address fields (village, post office, tehsil, district, state, pincode) and require pincode

Revision ID: ed3157643844
Revises: 89e132b515cb
Create Date: 2025-12-23 15:55:42.227961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed3157643844'
down_revision = '89e132b515cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_village', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address_post_office', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address_tehsil', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address_district', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address_state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address_pincode', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('address_pincode')
        batch_op.drop_column('address_state')
        batch_op.drop_column('address_district')
        batch_op.drop_column('address_tehsil')
        batch_op.drop_column('address_post_office')
        batch_op.drop_column('address_village')

    # ### end Alembic commands ###
