"""Add password field to customers table

Revision ID: ee9e988693fc
Revises: d06e3f1df9ab
Create Date: 2025-10-24 13:21:09.102903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9e988693fc'
down_revision = 'd06e3f1df9ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
    
    # Update existing records to have a default password
    from werkzeug.security import generate_password_hash
    default_password = generate_password_hash('default123')
    op.execute(f"UPDATE customers SET password_hash = '{default_password}' WHERE password_hash IS NULL")
    
    # Now make the column NOT NULL
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('password_hash', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
