"""Add missing M2 fields for complete account type management

Revision ID: fb4b538d3a81
Revises: a81326ec6239
Create Date: 2025-10-25 13:19:06.711953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4b538d3a81'
down_revision = 'a81326ec6239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_types', schema=None) as batch_op:
        # Add nullable columns first
        batch_op.add_column(sa.Column('deposit_limit_daily', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('deposit_limit_monthly', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('atm_withdrawal_limit_daily', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('minimum_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('low_balance_penalty', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('interest_calculation_frequency', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('interest_calculation_method', sa.String(length=20), nullable=True))
    
    # Update existing records with default values
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE account_types SET 
            minimum_balance = 0.0,
            low_balance_penalty = 0.0,
            interest_calculation_method = 'simple'
        WHERE minimum_balance IS NULL
    """))
    
    # Now make the required columns NOT NULL
    with op.batch_alter_table('account_types', schema=None) as batch_op:
        batch_op.alter_column('minimum_balance', nullable=False)
        batch_op.alter_column('low_balance_penalty', nullable=False)
        batch_op.alter_column('interest_calculation_method', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_types', schema=None) as batch_op:
        batch_op.drop_column('interest_calculation_method')
        batch_op.drop_column('interest_calculation_frequency')
        batch_op.drop_column('low_balance_penalty')
        batch_op.drop_column('minimum_balance')
        batch_op.drop_column('atm_withdrawal_limit_daily')
        batch_op.drop_column('deposit_limit_monthly')
        batch_op.drop_column('deposit_limit_daily')

    # ### end Alembic commands ###
